package br.com.quiz.service;

public class TemplateEmail {
	
	public static String montaTemplate(String nomeUsuario, Long codigoQuiz) {
		String template = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html\r\n"
				+ "  xmlns=\"http://www.w3.org/1999/xhtml\"\r\n"
				+ "  xmlns:o=\"urn:schemas-microsoft-com:office:office\"\r\n"
				+ ">\r\n"
				+ "  <head>\r\n"
				+ "    <meta charset=\"UTF-8\" />\r\n"
				+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\" />\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
				+ "    <meta content=\"telephone=no\" name=\"format-detection\" />\r\n"
				+ "    <title></title>\r\n"
				+ "    <!--[if (mso 16)]>\r\n"
				+ "      <style type=\"text/css\">\r\n"
				+ "        a {\r\n"
				+ "          text-decoration: none;\r\n"
				+ "        }\r\n"
				+ "      </style>\r\n"
				+ "    <![endif]-->\r\n"
				+ "    <!--[if gte mso 9\r\n"
				+ "      ]><style>\r\n"
				+ "        sup {\r\n"
				+ "          font-size: 100% !important;\r\n"
				+ "        }\r\n"
				+ "      </style><!\r\n"
				+ "    [endif]-->\r\n"
				+ "    <!--[if gte mso 9]>\r\n"
				+ "      <xml>\r\n"
				+ "        <o:OfficeDocumentSettings>\r\n"
				+ "          <o:AllowPNG></o:AllowPNG>\r\n"
				+ "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "        </o:OfficeDocumentSettings>\r\n"
				+ "      </xml>\r\n"
				+ "    <![endif]-->\r\n"
				+ "  </head>\r\n"
				+ "\r\n"
				+ "  <body>\r\n"
				+ "    <div class=\"es-wrapper-color\">\r\n"
				+ "      <!--[if gte mso 9]>\r\n"
				+ "        <v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
				+ "          <v:fill\r\n"
				+ "            type=\"tile\"\r\n"
				+ "            color=\"#d5a6bd\"\r\n"
				+ "            origin=\"0.5, 0\"\r\n"
				+ "            position=\"0.5, 0\"\r\n"
				+ "          ></v:fill>\r\n"
				+ "        </v:background>\r\n"
				+ "      <![endif]-->\r\n"
				+ "      <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"height: 50px;\">\r\n"
				+ "        <tbody>\r\n"
				+ "          <tr>\r\n"
				+ "            <td class=\"esd-email-paddings\" valign=\"top\">\r\n"
				+ "              <table\r\n"
				+ "                cellpadding=\"0\"\r\n"
				+ "                cellspacing=\"0\"\r\n"
				+ "                class=\"esd-header-popover es-header\"\r\n"
				+ "                align=\"center\"\r\n"
				+ "              >\r\n"
				+ "                <tbody>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td class=\"esd-stripe\" align=\"center\">\r\n"
				+ "                      <table\r\n"
				+ "                        bgcolor=\"rgba(0, 0, 0, 0)\"\r\n"
				+ "                        class=\"es-header-body\"\r\n"
				+ "                        align=\"center\"\r\n"
				+ "                        cellpadding=\"0\"\r\n"
				+ "                        cellspacing=\"0\"\r\n"
				+ "                        width=\"440\"\r\n"
				+ "                      >\r\n"
				+ "                        <tbody>\r\n"
				+ "                          <tr>\r\n"
				+ "                            <td\r\n"
				+ "                              class=\"esd-structure es-p20t es-p20r es-p20l\"\r\n"
				+ "                              align=\"left\"\r\n"
				+ "                              style=\"background-color: #af7790; display: flex; height: 150px; justify-content: space-around;\"\r\n"
				+ "                            >\r\n"
				+ "                              <!--[if mso]><table width=\"400\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"100\" valign=\"top\"><![endif]-->\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                class=\"es-left\"\r\n"
				+ "                                align=\"left\"\r\n style=\"display: flex;align-items: center;\""
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"100\"\r\n"
				+ "                                      class=\"es-m-p0r es-m-p20b esd-container-frame\"\r\n"
				+ "                                      valign=\"top\"\r\n"
				+ "                                      align=\"center\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-image\"\r\n"
				+ "                                              style=\"font-size: 0px\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <a target=\"_blank\"\r\n"
				+ "                                                ><img\r\n"
				+ "                                                  class=\"adapt-img\"\r\n"
				+ "                                                  src=\"https://demo.stripocdn.email/content/guids/af06dc17-2924-495b-a2a8-18985add654c/images/logocerto.png\"\r\n"
				+ "                                                  alt\r\n"
				+ "                                                  style=\"display: block; margin: auto;\"\r\n"
				+ "                                                  width=\"100\"\r\n"
				+ "                                              /></a>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                              <!--[if mso]></td><td width=\"20\"></td><td width=\"280\" valign=\"top\"><![endif]-->\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                align=\"right\"\r\n"
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"280\"\r\n"
				+ "                                      align=\"left\"\r\n"
				+ "                                      class=\"esd-container-frame\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-text es-p40t es-p40b es-p40r\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <p\r\n"
				+ "                                                style=\"\r\n"
				+ "                                                  color: #ffffff;\r\n"
				+ "                                                  font-size: 32px;\r\n"
				+ "                                                  font-family: 'Gill Sans',\r\n"
				+ "                                                    'Gill Sans MT', Calibri,\r\n"
				+ "                                                    'Trebuchet MS', sans-serif;\r\n"
				+ "                                                \"\r\n"
				+ "                                              >\r\n"
				+ "                                                <strong>ABA-QUIZ</strong>\r\n"
				+ "                                              </p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                              <!--[if mso]></td></tr></table><![endif]-->\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </tbody>\r\n"
				+ "              </table>\r\n"
				+ "              <table\r\n"
				+ "                cellpadding=\"0\"\r\n"
				+ "                cellspacing=\"0\"\r\n"
				+ "                class=\"es-content\"\r\n"
				+ "                align=\"center\"\r\n"
				+ "              >\r\n"
				+ "                <tbody>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td\r\n"
				+ "                      class=\"esd-stripe\"\r\n"
				+ "                      align=\"center\"\r\n"
				+ "                      bgcolor=\"#ffffff\"\r\n"
				+ "                      style=\"background-color: #c9cad1\"\r\n"
				+ "                    >\r\n"
				+ "                      <table\r\n"
				+ "                        bgcolor=\"transparent\"\r\n"
				+ "                        class=\"es-content-body\"\r\n"
				+ "                        align=\"center\"\r\n"
				+ "                        cellpadding=\"0\"\r\n"
				+ "                        cellspacing=\"0\"\r\n"
				+ "                        width=\"440\"\r\n"
				+ "                        style=\"background-color: transparent\"\r\n"
				+ "                      >\r\n"
				+ "                        <tbody>\r\n"
				+ "                          <tr>\r\n"
				+ "                            <td\r\n"
				+ "                              class=\"esd-structure es-p20t es-p10b es-p20r es-p20l\"\r\n"
				+ "                              align=\"left\"\r\n"
				+ "                              style=\"background-color: transparent\"\r\n"
				+ "                            >\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                width=\"100%\"\r\n"
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"400\"\r\n"
				+ "                                      class=\"esd-container-frame\"\r\n"
				+ "                                      align=\"center\"\r\n"
				+ "                                      valign=\"top\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              style=\"color: #3d0c6b\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <h4\r\n"
				+ "                                                style=\"\r\n"
				+ "                                                  font-family: 'Gill Sans',\r\n"
				+ "                                                    'Gill Sans MT', Calibri,\r\n"
				+ "                                                    'Trebuchet MS', sans-serif;\r\n"
				+ "                                                  font-weight: lighter;\r\n"
				+ "                                                  font-size: 18px;\r\n"
				+ "                                                \"\r\n"
				+ "                                              >\r\n"
				+ "                                                VOCÊ RECEBEU UM CONVITE DE\r\n"
				+ "                                                <br />\r\n"
				+ "                                                <span\r\n"
				+ "                                                  style=\"\r\n"
				+ "                                                    font-size: 28px;\r\n"
				+ "                                                    font-weight: bold;\r\n"
				+ "                                                  \"\r\n"
				+ "                                                >"+nomeUsuario+" </span\r\n"
				+ "                                                > <br />\r\n"
				+ "                                                PARA PARTICIPAR DE UM QUIZ\r\n"
				+ "                                              </h4>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                          <tr>\r\n"
				+ "                            <td\r\n"
				+ "                              class=\"esd-structure es-p15t es-m-p15t es-m-p0b es-m-p0r es-m-p0l\"\r\n"
				+ "                              align=\"left\"\r\n"
				+ "                            >\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                width=\"100%\"\r\n"
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"440\"\r\n"
				+ "                                      class=\"esd-container-frame\"\r\n"
				+ "                                      align=\"center\"\r\n"
				+ "                                      valign=\"top\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-image\"\r\n"
				+ "                                              style=\"font-size: 0px\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <a target=\"_blank\"\r\n"
				+ "                                                ><img\r\n"
				+ "                                                  class=\"adapt-img\"\r\n"
				+ "                                                  src=\"https://hpy.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/3991592481152831.png\"\r\n"
				+ "                                                  alt\r\n"
				+ "                                                  style=\"display: block\"\r\n"
				+ "                                                  width=\"440\"\r\n"
				+ "                                              /></a>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </tbody>\r\n"
				+ "              </table>\r\n"
				+ "              <table\r\n"
				+ "                cellpadding=\"0\"\r\n"
				+ "                cellspacing=\"0\"\r\n"
				+ "                class=\"es-content\"\r\n"
				+ "                align=\"center\"\r\n"
				+ "              >\r\n"
				+ "                <tbody>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td\r\n"
				+ "                      class=\"esd-stripe\"\r\n"
				+ "                      align=\"center\"\r\n"
				+ "                      bgcolor=\"#ead1dc\"\r\n"
				+ "                      style=\"\r\n"
				+ "                        background-color: #ead1dc;\r\n"
				+ "                        background-image: url(https://hpy.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/10801592857268437.png);\r\n"
				+ "                        background-repeat: no-repeat;\r\n"
				+ "                        background-position: center top;\r\n"
				+ "                      \"\r\n"
				+ "                      background=\"https://hpy.stripocdn.email/content/guids/CABINET_1ce849b9d6fc2f13978e163ad3c663df/images/10801592857268437.png\"\r\n"
				+ "                    >\r\n"
				+ "                      <table\r\n"
				+ "                        bgcolor=\"#ffffff\"\r\n"
				+ "                        class=\"es-content-body\"\r\n"
				+ "                        align=\"center\"\r\n"
				+ "                        cellpadding=\"0\"\r\n"
				+ "                        cellspacing=\"0\"\r\n"
				+ "                        width=\"440\"\r\n"
				+ "                        style=\"\r\n"
				+ "                          border-left: 10px solid transparent;\r\n"
				+ "                          border-right: 10px dashed transparent;\r\n"
				+ "                          border-top: 10px dashed transparent;\r\n"
				+ "                          border-bottom: 2px solid transparent;\r\n"
				+ "                          background-color: #c9cad1;\r\n"
				+ "                        \"\r\n"
				+ "                      >\r\n"
				+ "                        <tbody>\r\n"
				+ "                          <tr>\r\n"
				+ "                            <td\r\n"
				+ "                              class=\"esd-structure es-p40t es-p40b es-p30r es-p30l\"\r\n"
				+ "                              align=\"left\"\r\n"
				+ "                            >\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                width=\"100%\"\r\n"
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"360\"\r\n"
				+ "                                      class=\"esd-container-frame\"\r\n"
				+ "                                      align=\"center\"\r\n"
				+ "                                      valign=\"top\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-spacer\"\r\n"
				+ "                                              height=\"20\"\r\n"
				+ "                                            ></td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"left\"\r\n"
				+ "                                              class=\"esd-block-text es-p10b\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <h5\r\n"
				+ "                                                style=\"\r\n"
				+ "                                                  text-align: center;\r\n"
				+ "                                                  color: #3d0c6b;\r\n"
				+ "                                                  font-family: 'Gill Sans',\r\n"
				+ "                                                    'Gill Sans MT', Calibri,\r\n"
				+ "                                                    'Trebuchet MS', sans-serif;\r\n"
				+ "                                                \"\r\n"
				+ "                                              >\r\n"
				+ "                                                <b></b>&nbsp;<span\r\n"
				+ "                                                  style=\"\r\n"
				+ "                                                    font-size: 18px;\r\n"
				+ "                                                    font-weight: lighter;\r\n"
				+ "                                                  \"\r\n"
				+ "                                                  >VENHA PARTICIPAR DE UM QUIZ\r\n"
				+ "                                                  COM PERGUNTAS SELECIONADOS E\r\n"
				+ "                                                  PENSADAS PARA&nbsp;VOCÊ!</span\r\n"
				+ "                                                ><b></b>\r\n"
				+ "                                              </h5>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-button\"\r\n"
				+ "                                              style=\"background-color: #c9cad1\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <span\r\n"
				+ "                                                class=\"es-button-border es-button-border-1653361718585\"\r\n"
				+ "                                                style=\"\r\n"
				+ "                                                  background: #741b47;\r\n"
				+ "                                                  border-radius: 15px;\r\n"
				+ "                                                  padding: 10px;\r\n"
				+ "                                                  color: #ffffff;\r\n"
				+ "                                                \"\r\n"
				+ "                                                ><a\r\n"
				+ "                                                  href=\"http://localhost:8080/quiz\"\r\n"
				+ "                                                  class=\"es-button es-button-1653361718556\"\r\n"
				+ "                                                  target=\"_blank\"\r\n"
				+ "                                                  style=\"\r\n"
				+ "                                                    color: #ffffff;\r\n"
				+ "                                                    text-decoration: none;\r\n"
				+ "                                                    font-family: 'Gill Sans',\r\n"
				+ "                                                      'Gill Sans MT', Calibri,\r\n"
				+ "                                                      'Trebuchet MS', sans-serif;\r\n"
				+ "                                                  \"\r\n"
				+ "                                                  >ACESSAR QUIZ</a\r\n"
				+ "                                                ></span\r\n"
				+ "                                              >\r\n"
				+ "                                              <esd-config-block\r\n"
				+ "                                                value='{\"configClass\":\"es-button-1653361718556\",\"rule\":\"td .es-button-border:hover a.es-button-1653361718556\",\"properties\":{\"background\":\"#9c2460 !important\",\"border-color\":\"#9c2460 !important\"}}'\r\n"
				+ "                                                name=\"hoverColorButtonSettingsControl\"\r\n"
				+ "                                                style=\"display: none\"\r\n"
				+ "                                              ></esd-config-block>\r\n"
				+ "                                              <esd-config-block\r\n"
				+ "                                                value='{\"configClass\":\"es-button-border-1653361718585\",\"rule\":\"td .es-button-border-1653361718585:hover\",\"properties\":{\"background\":\"#9c2460 !important\"}}'\r\n"
				+ "                                                name=\"btnHoverOutlineStyleSettingsControl\"\r\n"
				+ "                                                style=\"display: none\"\r\n"
				+ "                                              ></esd-config-block>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </tbody>\r\n"
				+ "              </table>\r\n"
				+ "              <table\r\n"
				+ "                cellpadding=\"0\"\r\n"
				+ "                cellspacing=\"0\"\r\n"
				+ "                class=\"es-content esd-footer-popover\"\r\n"
				+ "                align=\"center\"\r\n"
				+ "              >\r\n"
				+ "                <tbody>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td class=\"esd-stripe\" align=\"center\">\r\n"
				+ "                      <table\r\n"
				+ "                        bgcolor=\"transparent\"\r\n"
				+ "                        class=\"es-content-body\"\r\n"
				+ "                        align=\"center\"\r\n"
				+ "                        cellpadding=\"0\"\r\n"
				+ "                        cellspacing=\"0\"\r\n"
				+ "                        width=\"440\"\r\n"
				+ "                      >\r\n"
				+ "                        <tbody>\r\n"
				+ "                          <tr>\r\n"
				+ "                            <td\r\n"
				+ "                              class=\"es-p20t es-p20r es-p20l esd-structure\"\r\n"
				+ "                              align=\"left\"\r\n"
				+ "                            >\r\n"
				+ "                              <table\r\n"
				+ "                                cellpadding=\"0\"\r\n"
				+ "                                cellspacing=\"0\"\r\n"
				+ "                                width=\"100%\"\r\n"
				+ "                              >\r\n"
				+ "                                <tbody>\r\n"
				+ "                                  <tr>\r\n"
				+ "                                    <td\r\n"
				+ "                                      width=\"400\"\r\n"
				+ "                                      class=\"esd-container-frame\"\r\n"
				+ "                                      align=\"center\"\r\n"
				+ "                                      valign=\"top\"\r\n"
				+ "                                    >\r\n"
				+ "                                      <table\r\n"
				+ "                                        cellpadding=\"0\"\r\n"
				+ "                                        cellspacing=\"0\"\r\n"
				+ "                                        width=\"100%\"\r\n"
				+ "                                      >\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                          <tr>\r\n"
				+ "                                            <td\r\n"
				+ "                                              align=\"center\"\r\n"
				+ "                                              class=\"esd-block-text es-p35\"\r\n"
				+ "                                            >\r\n"
				+ "                                              <p\r\n"
				+ "                                                style=\"\r\n"
				+ "                                                  color: #ffffff;\r\n"
				+ "                                                  background-color: #c5819f;\r\n"
				+ "                                                  font-family: 'Gill Sans',\r\n"
				+ "                                                    'Gill Sans MT', Calibri,\r\n"
				+ "                                                    'Trebuchet MS', sans-serif;\r\n"
				+ "                                                \"\r\n"
				+ "                                              >\r\n"
				+ "                                                Ou acesse<br />www.abaquiz.com.br&nbsp;\r\n"
				+ "                                                &nbsp;<br />e digite o seu\r\n"
				+ "                                                código de Quiz<br /><br /><span\r\n"
				+ "                                                  style=\"font-size: 24px\"\r\n"
				+ "                                                  >"+codigoQuiz+"</span\r\n"
				+ "                                                ><br />&nbsp; &nbsp; &nbsp;\r\n"
				+ "                                              </p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                          </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                      </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </tbody>\r\n"
				+ "              </table>\r\n"
				+ "            </td>\r\n"
				+ "          </tr>\r\n"
				+ "        </tbody>\r\n"
				+ "      </table>\r\n"
				+ "    </div>\r\n"
				+ "  </body>\r\n"
				+ "</html>\r\n"
				+ "";
		
		
		return template;
		
	}

}
