package br.com.quiz.service;

public class TemplateEmailNovo {
	
	public static String montaTemplate(String nomeUsuario, Long codigoQuiz) {
		String template = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "  <head>\r\n"
				+ "    <meta charset=\"UTF-8\" />\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n"
				+ "    <title>ABA-QUIZ</title>\r\n"
				+ "  </head>\r\n"
				+ "  <body>\r\n"
				+ "    <table\r\n"
				+ "      cellpadding=\"0\"\r\n"
				+ "      cellspacing=\"0\"\r\n"
				+ "      class=\"es-content esd-footer-popover\"\r\n"
				+ "      align=\"center\"\r\n"
				+ "      style=\"background-color: #421553\"\r\n"
				+ "    >\r\n"
				+ "      <tbody>\r\n"
				+ "        <tr>\r\n"
				+ "          <td\r\n"
				+ "            class=\"esd-stripe\"\r\n"
				+ "            align=\"center\"\r\n"
				+ "            bgcolor=\"#f8f9fd\"\r\n"
				+ "            style=\"background-color: #f8f9fd\"\r\n"
				+ "          >\r\n"
				+ "            <table\r\n"
				+ "              bgcolor=\"#ddd6d6\"\r\n"
				+ "              class=\"es-content-body\"\r\n"
				+ "              align=\"center\"\r\n"
				+ "              cellpadding=\"0\"\r\n"
				+ "              cellspacing=\"0\"\r\n"
				+ "              width=\"600\"\r\n"
				+ "            >\r\n"
				+ "              <tbody>\r\n"
				+ "                <!-- CABECALHO -->\r\n"
				+ "                <tr>\r\n"
				+ "                  <td\r\n"
				+ "                    class=\"esd-structure es-p40t es-p15b es-p20r es-p20l\"\r\n"
				+ "                    align=\"left\"\r\n"
				+ "                  >\r\n"
				+ "                    <table\r\n"
				+ "                      cellpadding=\"0\"\r\n"
				+ "                      cellspacing=\"0\"\r\n"
				+ "                      width=\"100%\"\r\n"
				+ "                      bgcolor=\"#7d0c6b\"\r\n"
				+ "                    >\r\n"
				+ "                      <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td\r\n"
				+ "                            width=\"281\"\r\n"
				+ "                            class=\"esd-container-frame\"\r\n"
				+ "                            align=\"center\"\r\n"
				+ "                            valign=\"top\"\r\n"
				+ "                          >\r\n"
				+ "                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                              <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                  <td align=\"left\" class=\"esd-block-text\">\r\n"
				+ "                                    <a\r\n"
				+ "                                      target=\"_blank\"\r\n"
				+ "                                      href=\"http://localhost:8080/quiz\"\r\n"
				+ "                                      ><img\r\n"
				+ "                                        class=\"adapt-img\"\r\n"
				+ "                                        src=\"https://demo.stripocdn.email/content/guids/af06dc17-2924-495b-a2a8-18985add654c/images/logocerto.png\"\r\n\""
				+ "                                        alt\r\n"
				+ "                                        style=\"display: block he\"\r\n"
				+ "                                        width=\"80\"\r\n"
				+ "                                    /></a>\r\n"
				+ "                                  </td>\r\n"
				+ "                                  <td\r\n"
				+ "                                    align=\"left\"\r\n"
				+ "                                    class=\"esd-block-text\"\r\n"
				+ "                                    style=\"\r\n"
				+ "                                      color: #ffffff;\r\n"
				+ "                                      font-size: 25px;\r\n"
				+ "                                      font-family: 'Gill Sans', 'Gill Sans MT',\r\n"
				+ "                                        Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "                                      font-weight: bolder;\r\n"
				+ "                                    \"\r\n"
				+ "                                  >\r\n"
				+ "                                    <p>ABA-QUIZ</p>\r\n"
				+ "                                  </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                              </tbody>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "\r\n"
				+ "                <!-- CORPO -->\r\n"
				+ "\r\n"
				+ "                <tr>\r\n"
				+ "                  <td align=\"left\" width=\"600\">\r\n"
				+ "                    <table\r\n"
				+ "                      cellpadding=\"0\"\r\n"
				+ "                      cellspacing=\"0\"\r\n"
				+ "                      width=\"100%\"\r\n"
				+ "                      bgcolor=\"#ddd6d6\"\r\n"
				+ "                    >\r\n"
				+ "                      <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"center\" style=\"color: #3d0c6b\">\r\n"
				+ "                            <h4\r\n"
				+ "                              style=\"\r\n"
				+ "                                font-family: 'Gill Sans', 'Gill Sans MT',\r\n"
				+ "                                  Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "                                font-weight: lighter;\r\n"
				+ "                                font-size: 18px;\r\n"
				+ "                              \"\r\n"
				+ "                            >\r\n"
				+ "                              VOCÊ RECEBEU UM CONVITE DE\r\n"
				+ "                              <br />\r\n"
				+ "                              <span style=\"font-size: 28px; font-weight: bold\">\r\n"
				+ "                               "+nomeUsuario+" </span\r\n"
				+ "                              ><br />\r\n"
				+ "                              PARA PARTICIPAR DE UM QUIZ\r\n"
				+ "                            </h4>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "                <tr>\r\n"
				+ "                  <td align=\"left\" width=\"600\">\r\n"
				+ "                    <table\r\n"
				+ "                      cellpadding=\"0\"\r\n"
				+ "                      cellspacing=\"0\"\r\n"
				+ "                      width=\"100%\"\r\n"
				+ "                      bgcolor=\"#ddd6d6\"\r\n"
				+ "                    >\r\n"
				+ "                      <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"center\" style=\"color: #3d0c6b\">\r\n"
				+ "                            <h5\r\n"
				+ "                              style=\"\r\n"
				+ "                                text-align: center;\r\n"
				+ "                                color: #3d0c6b;\r\n"
				+ "                                font-family: 'Gill Sans', 'Gill Sans MT',\r\n"
				+ "                                  Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "                              \"\r\n"
				+ "                            >\r\n"
				+ "                              <b></b>&nbsp;<span\r\n"
				+ "                                style=\"font-size: 18px; font-weight: lighter\"\r\n"
				+ "                                >VENHA PARTICIPAR DE UM QUIZ COM PERGUNTAS\r\n"
				+ "                                SELECIONADOS E PENSADAS PARA&nbsp;VOCÊ!</span\r\n"
				+ "                              ><b></b>\r\n"
				+ "                            </h5>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "                <tr>\r\n"
				+ "                  <td align=\"left\" width=\"600\">\r\n"
				+ "                    <table\r\n"
				+ "                      cellpadding=\"0\"\r\n"
				+ "                      cellspacing=\"0\"\r\n"
				+ "                      width=\"100%\"\r\n"
				+ "                      bgcolor=\"#ddd6d6\"\r\n"
				+ "                      style=\"margin-top: 50px\"\r\n"
				+ "                    >\r\n"
				+ "                      <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"center\" style=\"color: #3d0c6b\">\r\n"
				+ "                            <span\r\n"
				+ "                              class=\"es-button-border es-button-border-1653361718585\"\r\n"
				+ "                              style=\"\r\n"
				+ "                                background: #741b47;\r\n"
				+ "                                border-radius: 15px;\r\n"
				+ "                                padding: 10px;\r\n"
				+ "                                color: #ffffff;\r\n"
				+ "                              \"\r\n"
				+ "                              ><a\r\n"
				+ "                                href=\"http://localhost:8080/quiz\"\r\n"
				+ "                                class=\"es-button es-button-1653361718556\"\r\n"
				+ "                                target=\"_blank\"\r\n"
				+ "                                style=\"\r\n"
				+ "                                  color: #ffffff;\r\n"
				+ "                                  text-decoration: none;\r\n"
				+ "                                  font-family: 'Gill Sans', 'Gill Sans MT',\r\n"
				+ "                                    Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "                                \"\r\n"
				+ "                                >ACESSAR QUIZ</a\r\n"
				+ "                              ></span\r\n"
				+ "                            >\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "                <tr>\r\n"
				+ "                  <td align=\"left\" width=\"600\">\r\n"
				+ "                    <table\r\n"
				+ "                      cellpadding=\"0\"\r\n"
				+ "                      cellspacing=\"0\"\r\n"
				+ "                      width=\"100%\"\r\n"
				+ "                      bgcolor=\"#ddd6d6\"\r\n"
				+ "                      style=\"margin-top: 50px\"\r\n"
				+ "                    >\r\n"
				+ "                      <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"center\" style=\"color: #3b1249\">\r\n"
				+ "                            <p\r\n"
				+ "                              style=\"\r\n"
				+ "                                color: #ffffff;\r\n"
				+ "                                background-color: #641453\";\r\n"
				+ "                                font-family: 'Gill Sans', 'Gill Sans MT',\r\n"
				+ "                                  Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "                              \"\r\n"
				+ "                            >\r\n"
				+ "                              Ou acesse<br />www.abaquiz.com.br&nbsp; &nbsp;<br />e\r\n"
				+ "                              digite o seu código de Quiz<br /><br /><span\r\n"
				+ "                                style=\"font-size: 24px\"\r\n"
				+ "                                >"+codigoQuiz+"</span\r\n"
				+ "                              ><br />&nbsp; &nbsp; &nbsp;\r\n"
				+ "                            </p>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "              </tbody>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "        </tr>\r\n"
				+ "      </tbody>\r\n"
				+ "    </table>\r\n"
				+ "  </body>\r\n"
				+ "</html>\r\n"
				+ "";
		
		
		return template;
	}
}
